print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("same arrow with duplicate lines removed")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("same arrow, twice the size")
print("    *\n\n   * *\n\n  *   *\n\n *     *\n\n***   ***\n\n  *   *\n\n  *   *\n\n  *****")
print()
print(("     * ")*2)
print(("    * * ")*2)
print(("   *   * ")*2)
print(("  *     * ")*2)
print((" ***   *** ")*2)
print(("   *   * ")*2)
print(("   *   * ")*2)
print(("   ***** ")*2)
